# Generated by Django 5.1 on 2024-10-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0007_alter_comment_fk_user_alter_fileupload_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='endereco',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='datanascimento',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='name',
        ),
    ]
