# Generated by Django 5.1 on 2024-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0009_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='usuario',
            name='birthname',
            field=models.DateField(blank=True, null=True),
        ),
    ]
