# Generated by Django 5.1 on 2024-10-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0010_remove_usuario_birthdate_usuario_birthname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='birthname',
            new_name='birthdate',
        ),
    ]
